{
  "uid" : "17beefd78bc0896e",
  "name" : "test_run[run_case0]",
  "fullName" : "testcase.TestKeywords.TestKeyword#test_run[run_case0]",
  "historyId" : "1b1458eb6c9578bbae1b78493d33e22c",
  "time" : {
    "start" : 1589161429651,
    "stop" : 1589161429651,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'run' is not defined",
  "statusTrace" : "cmdopt = 'run'\n\n    @pytest.fixture(scope=\"session\")\n    def start_appium_desired(cmdopt):\n>       opt = eval(cmdopt)\nE       NameError: name 'run' is not defined\n\ntestcase\\conftest.py:21: NameError",
  "flaky" : true,
  "beforeStages" : [ {
    "name" : "start_appium_desired",
    "time" : {
      "start" : 1589161429652,
      "stop" : 1589161429652,
      "duration" : 0
    },
    "status" : "broken",
    "statusMessage" : "NameError: name 'run' is not defined\n",
    "statusTrace" : "  File \"C:\\Users\\cjj\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\cjj\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\cjj\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\cjj\\PycharmProjects\\Appium_AutoTest\\testcase\\conftest.py\", line 21, in start_appium_desired\n    opt = eval(cmdopt)\n  File \"<string>\", line 1, in <module>\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0
  }, {
    "name" : "cmdopt",
    "time" : {
      "start" : 1589161429652,
      "stop" : 1589161429652,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "TestKeywords"
  }, {
    "name" : "subSuite",
    "value" : "TestKeyword"
  }, {
    "name" : "host",
    "value" : "DESKTOP-0LL74L3"
  }, {
    "name" : "thread",
    "value" : "11040-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.TestKeywords"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "run_case",
    "value" : "{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13766667777,password=123456', '期望结果': '密码错误', '备注': '登录功能测试', '描述': '登录功能测试'}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "73b66c67fae04b22",
      "status" : "passed",
      "time" : {
        "start" : 1589161382720,
        "stop" : 1589161413042,
        "duration" : 30322
      }
    }, {
      "uid" : "10d24ce7f9f1f04e",
      "status" : "broken",
      "statusDetails" : "NameError: name 'run' is not defined",
      "time" : {
        "start" : 1589161356410,
        "stop" : 1589161356410,
        "duration" : 0
      }
    }, {
      "uid" : "32a9adecf79ff306",
      "status" : "broken",
      "statusDetails" : "AttributeError: 'NoneType' object has no attribute 'launch_app'",
      "time" : {
        "start" : 1589161356228,
        "stop" : 1589161356229,
        "duration" : 1
      }
    }, {
      "uid" : "31537fff88684905",
      "status" : "broken",
      "statusDetails" : "NameError: name 'run' is not defined",
      "time" : {
        "start" : 1589161162820,
        "stop" : 1589161162820,
        "duration" : 0
      }
    }, {
      "uid" : "47d0076ac1fb5c78",
      "status" : "failed",
      "statusDetails" : "AssertionError",
      "time" : {
        "start" : 1589161119857,
        "stop" : 1589161131145,
        "duration" : 11288
      }
    }, {
      "uid" : "26a282452db45668",
      "status" : "failed",
      "statusDetails" : "AssertionError",
      "time" : {
        "start" : 1589114374144,
        "stop" : 1589114386310,
        "duration" : 12166
      }
    }, {
      "uid" : "9e37a3014e9c1b69",
      "status" : "failed",
      "statusDetails" : "AssertionError",
      "time" : {
        "start" : 1589114304927,
        "stop" : 1589114317288,
        "duration" : 12361
      }
    }, {
      "uid" : "4530cbccd42269ed",
      "status" : "failed",
      "statusDetails" : "AssertionError",
      "time" : {
        "start" : 1589098268339,
        "stop" : 1589098276783,
        "duration" : 8444
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "17beefd78bc0896e.json",
  "parameterValues" : [ "{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13766667777,password=123456', '期望结果': '密码错误', '备注': '登录功能测试', '描述': '登录功能测试'}" ]
}